#!/bin/sh

case "$1" in
    start)
        /usr/bin/scull_load
        /usr/bin/module_load faulty
        modprobe hello
        ;;
    stop)
        /usr/bin/scull_unload
        /usr/bin/module_unload faulty
        rmmod hello
        ;;
    *)
        echo "Usage: ldd-modules {start|stop}"
        exit 1
        ;;
esac