#!/bin/sh

case "$1" in
    start)
        echo "Loading LDD modules..."
        # Fallback group if wheel/staff don't exist in /etc/group
        /usr/bin/scull_load
        /usr/bin/module_load faulty
        modprobe hello
        ;;
    stop)
        echo "Unloading LDD modules..."
        /usr/bin/module_unload faulty
        /usr/bin/scull_unload
        rmmod hello
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac